#!/usr/bin/env bash
# skill-audit.sh — walk all known skill paths on hephastus, emit a dated markdown report.
# Usage:
#   ./scripts/skill-audit.sh              # writes docs/skill-audit-YYYY-MM-DD.md + stdout
#   ./scripts/skill-audit.sh --stdout     # stdout only, no file written
#   ./scripts/skill-audit.sh --out PATH   # write to custom path

set -euo pipefail

DATE=$(date +%Y-%m-%d)
WRITE_FILE=true
OUT_PATH=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --stdout) WRITE_FILE=false; shift ;;
    --out)    OUT_PATH="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

if [[ -z "$OUT_PATH" && "$WRITE_FILE" == "true" ]]; then
  OUT_PATH="$REPO_ROOT/docs/skill-audit-$DATE.md"
fi

HOME_UNIX="${HOME:-/c/Users/pmacl}"
PROJECTS="/d/_projects"

# ── helpers ───────────────────────────────────────────────────────────────────

count_skills() {
  # Count directories containing a SKILL.md under $1 (max depth 6)
  local dir="$1"
  [[ -d "$dir" ]] || { echo 0; return; }
  find "$dir" -maxdepth 6 -name "SKILL.md" 2>/dev/null | wc -l | tr -d ' '
}

list_skills() {
  # Print each SKILL.md path relative to $1, one per line, indented
  local dir="$1"
  [[ -d "$dir" ]] || return
  find "$dir" -maxdepth 6 -name "SKILL.md" 2>/dev/null \
    | sed "s|$dir/||" \
    | sed 's|/SKILL\.md||' \
    | sort \
    | sed 's/^/  - /'
}

section() {
  printf '\n### %s\n' "$1"
  printf '**Path:** `%s`\n\n' "$2"
}

emit() { printf '%s\n' "$@"; }

# ── build report ──────────────────────────────────────────────────────────────

{
emit "# Skill Audit — hephastus"
emit "**Generated:** $DATE"
emit ""
emit "Auto-generated by \`scripts/skill-audit.sh\`. Re-run to refresh."
emit ""
emit "---"
emit ""
emit "## Tool-level skills"

# Claude Code — user
DIR="$HOME_UNIX/.claude/skills"
N=$(count_skills "$DIR")
section "Claude Code — user ($N skills)" "$DIR"
list_skills "$DIR"

# Claude Code — OMC package (oh-my-claude-sisyphus)
OMC_DIR=$(cygpath -u "$(npm root -g 2>/dev/null)" 2>/dev/null || npm root -g 2>/dev/null)/oh-my-claude-sisyphus/skills
N=$(count_skills "$OMC_DIR")
section "Claude Code — OMC package / oh-my-claude-sisyphus ($N skills)" "$OMC_DIR"
list_skills "$OMC_DIR"

# Kilo Code
DIR="$HOME_UNIX/.kilo/skills"
N=$(count_skills "$DIR")
section "Kilo Code ($N skills)" "$DIR"
list_skills "$DIR"

# Codex CLI — system
DIR="$HOME_UNIX/.codex/skills/.system"
N=$(count_skills "$DIR")
section "Codex CLI — system ($N skills)" "$DIR"
list_skills "$DIR"

# Codex CLI — user (skip .system)
DIR="$HOME_UNIX/.codex/skills"
N=0
CODEX_USER_LINES=""
if [[ -d "$DIR" ]]; then
  while IFS= read -r f; do
    skill=$(echo "$f" | sed "s|$DIR/||" | sed 's|/SKILL\.md||')
    [[ "$skill" == .system* ]] && continue
    N=$((N+1))
    CODEX_USER_LINES+="  - $skill"$'\n'
  done < <(find "$DIR" -maxdepth 2 -name "SKILL.md" 2>/dev/null | sort)
fi
section "Codex CLI — user ($N skills)" "$DIR"
printf '%s' "$CODEX_USER_LINES"

# Antigravity CLI
DIR="$HOME_UNIX/.gemini/antigravity-cli"
N=$(count_skills "$DIR")
section "Antigravity CLI ($N skills)" "$DIR"
list_skills "$DIR"

# Minimax Agent
DIR="$HOME_UNIX/.minimax-agent/projects/.minimax/skills"
N=$(count_skills "$DIR")
section "Minimax Agent ($N skills)" "$DIR"
list_skills "$DIR"

# Goose
DIR="$HOME_UNIX/.config/goose/skills"
N=$(count_skills "$DIR")
section "Goose ($N skills)" "$DIR"
if [[ $N -eq 0 ]]; then emit "  *(empty)*"; else list_skills "$DIR"; fi

# KimiClaw
DIR="$HOME_UNIX/Downloads/KimiClaw/skills"
N=$(count_skills "$DIR")
section "KimiClaw ($N skills)" "$DIR"
list_skills "$DIR"

# Downloads loose skills
DIR="$HOME_UNIX/Downloads/skills"
section "Downloads loose skills" "$DIR"
if [[ -d "$DIR" ]]; then
  find "$DIR" -maxdepth 1 -mindepth 1 2>/dev/null | sed "s|$DIR/||" | sort | sed 's/^/  - /'
else
  emit "  *(not found)*"
fi

emit ""
emit "---"
emit ""
emit "## Project-level skills"

# frozenSkillz (this repo)
DIR="$REPO_ROOT"
N=$(find "$DIR" -path "*/skills/*/SKILL.md" -not -path "*/node_modules/*" 2>/dev/null | wc -l | tr -d ' ')
section "frozenSkillz — this repo ($N SKILL.md files)" "$DIR"
find "$DIR" -path "*/skills/*/SKILL.md" -not -path "*/node_modules/*" 2>/dev/null \
  | sed "s|$DIR/||" | sed 's|/SKILL\.md||' | sort | sed 's/^/  - /'

# Project dirs with .agents/skills or .claude/skills
PROJECT_DIRS=(
  "coldaine-infra:.claude/skills"
  "oh-my-openagent:.agents/skills"
  "oh-my-openagent:.opencode/skills"
  "ColdReviewer:.agents/skills"
  "ColdTools/ColdReviewer:.agents/skills"
  "ActuarialKnowledge:.agents/skills"
  "AgentVisualCrazy:.agents/skills"
  "llm-archiver:.agents/skills"
  "IdeaEmergence:.github/skills"
  "coldaine-ci-source/archive/codebuff/agents:skills"
)

for entry in "${PROJECT_DIRS[@]}"; do
  proj="${entry%%:*}"
  subdir="${entry##*:}"
  DIR="$PROJECTS/$proj/$subdir"
  N=$(count_skills "$DIR")
  section "$proj / $subdir ($N skills)" "$DIR"
  list_skills "$DIR"
done

# hermes-agent (large corpus — count by category)
DIR="$PROJECTS/hermes-agent/skills"
section "hermes-agent (large corpus — counts by category)" "$DIR"
if [[ -d "$DIR" ]]; then
  emit "| Category | SKILL/md files |"
  emit "|---|---|"
  find "$DIR" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | sort | while read -r cat; do
    n=$(find "$cat" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
    printf '| %s | %s |\n' "$(basename "$cat")" "$n"
  done
  total=$(find "$DIR" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
  emit ""
  emit "**Total:** $total md files"
else
  emit "  *(not found)*"
fi

emit ""
emit "---"
emit ""
emit "## Notes"
emit ""
emit "- Paths prefixed \`~/\` are relative to \`$HOME_UNIX\`."
emit "- Paths prefixed \`D:\\\\_projects\\\\\` are under \`$PROJECTS\`."
emit "- Codex \`.system\` skills are built-in (shipped with the tool); user skills are listed separately."
emit "- hermes-agent is a large upstream corpus, not locally maintained — shown as category counts only."
emit "- Re-run this script after installing or removing skills to get a fresh dated snapshot."

} | if [[ "$WRITE_FILE" == "true" ]]; then
  tee "$OUT_PATH"
  echo "" >&2
  echo "Written to: $OUT_PATH" >&2
else
  cat
fi
